version: 2
updates:
- package-ecosystem: gradle
  directories:
    - "/"
    - "/java-8"
    - "/android"
  schedule:
    interval: daily
    time: "09:00" # 9am UTC
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
    microsoft-graph:
      patterns:
        - "*microsoft-graph*"
    junit-dependencies:
      patterns:
        - "*junit*"
    open-telemetry:
      patterns:
        - "*opentelemetry*"
    android-build-tools:
      patterns:
        - "*android*"
        - "*gradle-enterprise*"
        - "*gradle-util*"
        - "*gradle-versions*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    all-actions:
      patterns:
        - "*"
