// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.concurrency.*;
import com.microsoft.graph.core.*;
import com.microsoft.graph.models.extensions.*;
import com.microsoft.graph.models.generated.*;
import com.microsoft.graph.models.extensions.DriveRecipient;
import com.microsoft.graph.http.*;
import com.microsoft.graph.requests.extensions.*;
import com.microsoft.graph.serializer.*;

import java.util.Arrays;
import java.util.EnumSet;

import com.google.gson.JsonObject;
import com.google.gson.annotations.*;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Drive Item Invite Collection Page.
 */
public class DriveItemInviteCollectionPage extends BaseCollectionPage<Permission, IDriveItemInviteCollectionRequestBuilder> implements IDriveItemInviteCollectionPage {

    /**
     * A collection page for DriveItemInvite.
     *
     * @param response The serialized DriveItemInviteCollectionResponse from the service
     * @param builder The request builder for the next collection page
     */
    public DriveItemInviteCollectionPage(final DriveItemInviteCollectionResponse response, final IDriveItemInviteCollectionRequestBuilder builder) {
       super(response.value, builder);
    }
}
