// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.FieldValueSet;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.options.QueryOption;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;
import com.microsoft.graph.core.IBaseClient;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Field Value Set Reference Request.
 */
public class FieldValueSetReferenceRequest extends BaseRequest implements IFieldValueSetReferenceRequest {

    /**
     * The request for the FieldValueSet
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public FieldValueSetReferenceRequest(String requestUrl, IBaseClient client, java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, FieldValueSet.class);
    }

    public void delete(final ICallback<? super FieldValueSet> callback) {
        send(HttpMethod.DELETE, callback, null);
    }

    public FieldValueSet delete() throws ClientException {
       return send(HttpMethod.DELETE, null);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    public IFieldValueSetReferenceRequest select(final String value) {
        getQueryOptions().add(new com.microsoft.graph.options.QueryOption("$select", value));
        return (FieldValueSetReferenceRequest)this;
    }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    public IFieldValueSetReferenceRequest expand(final String value) {
        getQueryOptions().add(new com.microsoft.graph.options.QueryOption("$expand", value));
        return (FieldValueSetReferenceRequest)this;
    }
    /**
     * Puts the FieldValueSet
     *
     * @param srcFieldValueSet the FieldValueSet reference to PUT
     * @param callback the callback to be called after success or failure
     */
    public void put(FieldValueSet srcFieldValueSet, final ICallback<? super FieldValueSet> callback) {
        send(HttpMethod.PUT, callback, srcFieldValueSet);
    }

    /**
     * Puts the FieldValueSet
     *
     * @param srcFieldValueSet the FieldValueSet reference to PUT
     * @return the FieldValueSet
     * @throws ClientException an exception occurs if there was an error while the request was sent
     */
    public FieldValueSet put(FieldValueSet srcFieldValueSet) throws ClientException {
        return send(HttpMethod.PUT, srcFieldValueSet);
    }
}
