// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.Contract;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.models.extensions.Contract;
import com.microsoft.graph.http.IHttpRequest;
import com.microsoft.graph.serializer.IJsonBackedObject;


// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Contract With Reference Request.
 */
public interface IContractWithReferenceRequest extends IHttpRequest {

    void post(final Contract newContract, final IJsonBackedObject payload, final ICallback<? super Contract> callback);

    Contract post(final Contract newContract, final IJsonBackedObject payload) throws ClientException;

    void get(final ICallback<? super Contract> callback);

    Contract get() throws ClientException;

	void delete(final ICallback<? super Contract> callback);

	void delete() throws ClientException;

	void patch(final Contract sourceContract, final ICallback<? super Contract> callback);

	Contract patch(final Contract sourceContract) throws ClientException;

    IContractWithReferenceRequest select(final String value);

    IContractWithReferenceRequest expand(final String value);

}
