// Template Source: IBaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.models.extensions.DeviceAppManagement;

import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.http.IHttpRequest;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Device App Management Request.
 */
public interface IDeviceAppManagementRequest extends IHttpRequest {

    /**
     * Gets the DeviceAppManagement from the service
     *
     * @param callback the callback to be called after success or failure
     */
    void get(final ICallback<? super DeviceAppManagement> callback);

    /**
     * Gets the DeviceAppManagement from the service
     *
     * @return the DeviceAppManagement from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    DeviceAppManagement get() throws ClientException;

    /**
     * Delete this item from the service
     *
     * @param callback the callback when the deletion action has completed
     */
    void delete(final ICallback<? super DeviceAppManagement> callback);

    /**
     * Delete this item from the service
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    void delete() throws ClientException;

    /**
     * Patches this DeviceAppManagement with a source
     *
     * @param sourceDeviceAppManagement the source object with updates
     * @param callback the callback to be called after success or failure
     */
    void patch(final DeviceAppManagement sourceDeviceAppManagement, final ICallback<? super DeviceAppManagement> callback);

    /**
     * Patches this DeviceAppManagement with a source
     *
     * @param sourceDeviceAppManagement the source object with updates
     * @return the updated DeviceAppManagement
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    DeviceAppManagement patch(final DeviceAppManagement sourceDeviceAppManagement) throws ClientException;

    /**
     * Posts a DeviceAppManagement with a new object
     *
     * @param newDeviceAppManagement the new object to create
     * @param callback the callback to be called after success or failure
     */
    void post(final DeviceAppManagement newDeviceAppManagement, final ICallback<? super DeviceAppManagement> callback);

    /**
     * Posts a DeviceAppManagement with a new object
     *
     * @param newDeviceAppManagement the new object to create
     * @return the created DeviceAppManagement
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    DeviceAppManagement post(final DeviceAppManagement newDeviceAppManagement) throws ClientException;

    /**
     * Posts a DeviceAppManagement with a new object
     *
     * @param newDeviceAppManagement the object to create/update
     * @param callback the callback to be called after success or failure
     */
    void put(final DeviceAppManagement newDeviceAppManagement, final ICallback<? super DeviceAppManagement> callback);

    /**
     * Posts a DeviceAppManagement with a new object
     *
     * @param newDeviceAppManagement the object to create/update
     * @return the created DeviceAppManagement
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    DeviceAppManagement put(final DeviceAppManagement newDeviceAppManagement) throws ClientException;

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    IDeviceAppManagementRequest select(final String value);

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    IDeviceAppManagementRequest expand(final String value);

}

