// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.ManagedAndroidStoreApp;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.models.extensions.ManagedAndroidStoreApp;
import com.microsoft.graph.http.IHttpRequest;
import com.microsoft.graph.serializer.IJsonBackedObject;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Managed Android Store App Reference Request.
 */
public interface IManagedAndroidStoreAppReferenceRequest extends IHttpRequest {

    void delete(final ICallback<? super ManagedAndroidStoreApp> callback);

    ManagedAndroidStoreApp delete() throws ClientException;

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    IManagedAndroidStoreAppReferenceRequest select(final String value);

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    IManagedAndroidStoreAppReferenceRequest expand(final String value);

    /**
     * Puts the ManagedAndroidStoreApp
     *
     * @param srcManagedAndroidStoreApp the ManagedAndroidStoreApp to PUT
     * @param callback the callback to be called after success or failure
     */
    void put(ManagedAndroidStoreApp srcManagedAndroidStoreApp, final ICallback<? super ManagedAndroidStoreApp> callback);

    /**
     * Puts the ManagedAndroidStoreApp
     *
     * @param srcManagedAndroidStoreApp the ManagedAndroidStoreApp to PUT
     * @return the ManagedAndroidStoreApp
     * @throws ClientException an exception occurs if there was an error while the request was sent
     */
    ManagedAndroidStoreApp put(ManagedAndroidStoreApp srcManagedAndroidStoreApp) throws ClientException;
}
