// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.ManagedAppOperation;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.models.extensions.ManagedAppOperation;
import com.microsoft.graph.http.IHttpRequest;
import com.microsoft.graph.serializer.IJsonBackedObject;


// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Managed App Operation With Reference Request.
 */
public interface IManagedAppOperationWithReferenceRequest extends IHttpRequest {

    void post(final ManagedAppOperation newManagedAppOperation, final IJsonBackedObject payload, final ICallback<? super ManagedAppOperation> callback);

    ManagedAppOperation post(final ManagedAppOperation newManagedAppOperation, final IJsonBackedObject payload) throws ClientException;

    void get(final ICallback<? super ManagedAppOperation> callback);

    ManagedAppOperation get() throws ClientException;

	void delete(final ICallback<? super ManagedAppOperation> callback);

	void delete() throws ClientException;

	void patch(final ManagedAppOperation sourceManagedAppOperation, final ICallback<? super ManagedAppOperation> callback);

	ManagedAppOperation patch(final ManagedAppOperation sourceManagedAppOperation) throws ClientException;

    IManagedAppOperationWithReferenceRequest select(final String value);

    IManagedAppOperationWithReferenceRequest expand(final String value);

}
