// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.MobileAppAssignment;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.models.extensions.MobileAppAssignment;
import com.microsoft.graph.http.IHttpRequest;
import com.microsoft.graph.serializer.IJsonBackedObject;


// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Mobile App Assignment With Reference Request.
 */
public interface IMobileAppAssignmentWithReferenceRequest extends IHttpRequest {

    void post(final MobileAppAssignment newMobileAppAssignment, final IJsonBackedObject payload, final ICallback<? super MobileAppAssignment> callback);

    MobileAppAssignment post(final MobileAppAssignment newMobileAppAssignment, final IJsonBackedObject payload) throws ClientException;

    void get(final ICallback<? super MobileAppAssignment> callback);

    MobileAppAssignment get() throws ClientException;

	void delete(final ICallback<? super MobileAppAssignment> callback);

	void delete() throws ClientException;

	void patch(final MobileAppAssignment sourceMobileAppAssignment, final ICallback<? super MobileAppAssignment> callback);

	MobileAppAssignment patch(final MobileAppAssignment sourceMobileAppAssignment) throws ClientException;

    IMobileAppAssignmentWithReferenceRequest select(final String value);

    IMobileAppAssignmentWithReferenceRequest expand(final String value);

}
