// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.OnPremisesConditionalAccessSettings;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.models.extensions.OnPremisesConditionalAccessSettings;
import com.microsoft.graph.http.IHttpRequest;
import com.microsoft.graph.serializer.IJsonBackedObject;


// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the On Premises Conditional Access Settings With Reference Request.
 */
public interface IOnPremisesConditionalAccessSettingsWithReferenceRequest extends IHttpRequest {

    void post(final OnPremisesConditionalAccessSettings newOnPremisesConditionalAccessSettings, final IJsonBackedObject payload, final ICallback<? super OnPremisesConditionalAccessSettings> callback);

    OnPremisesConditionalAccessSettings post(final OnPremisesConditionalAccessSettings newOnPremisesConditionalAccessSettings, final IJsonBackedObject payload) throws ClientException;

    void get(final ICallback<? super OnPremisesConditionalAccessSettings> callback);

    OnPremisesConditionalAccessSettings get() throws ClientException;

	void delete(final ICallback<? super OnPremisesConditionalAccessSettings> callback);

	void delete() throws ClientException;

	void patch(final OnPremisesConditionalAccessSettings sourceOnPremisesConditionalAccessSettings, final ICallback<? super OnPremisesConditionalAccessSettings> callback);

	OnPremisesConditionalAccessSettings patch(final OnPremisesConditionalAccessSettings sourceOnPremisesConditionalAccessSettings) throws ClientException;

    IOnPremisesConditionalAccessSettingsWithReferenceRequest select(final String value);

    IOnPremisesConditionalAccessSettingsWithReferenceRequest expand(final String value);

}
