// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.PlayPromptOperation;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.models.extensions.PlayPromptOperation;
import com.microsoft.graph.http.IHttpRequest;
import com.microsoft.graph.serializer.IJsonBackedObject;


// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Play Prompt Operation With Reference Request.
 */
public interface IPlayPromptOperationWithReferenceRequest extends IHttpRequest {

    void post(final PlayPromptOperation newPlayPromptOperation, final IJsonBackedObject payload, final ICallback<? super PlayPromptOperation> callback);

    PlayPromptOperation post(final PlayPromptOperation newPlayPromptOperation, final IJsonBackedObject payload) throws ClientException;

    void get(final ICallback<? super PlayPromptOperation> callback);

    PlayPromptOperation get() throws ClientException;

	void delete(final ICallback<? super PlayPromptOperation> callback);

	void delete() throws ClientException;

	void patch(final PlayPromptOperation sourcePlayPromptOperation, final ICallback<? super PlayPromptOperation> callback);

	PlayPromptOperation patch(final PlayPromptOperation sourcePlayPromptOperation) throws ClientException;

    IPlayPromptOperationWithReferenceRequest select(final String value);

    IPlayPromptOperationWithReferenceRequest expand(final String value);

}
