// Template Source: IBaseMethodRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.requests.extensions.IWorkbookFunctionsRriRequest;

import com.microsoft.graph.http.IRequestBuilder;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Workbook Functions Rri Request Builder.
 */
public interface IWorkbookFunctionsRriRequestBuilder extends IRequestBuilder {

    /**
     * Creates the IWorkbookFunctionsRriRequest
     *
     * @param requestOptions the options for the request
     * @return the IWorkbookFunctionsRriRequest instance
     */
    IWorkbookFunctionsRriRequest buildRequest(final com.microsoft.graph.options.Option... requestOptions);

    /**
     * Creates the IWorkbookFunctionsRriRequest with specific options instead of the existing options
     *
     * @param requestOptions the options for the request
     * @return the IWorkbookFunctionsRriRequest instance
     */
    IWorkbookFunctionsRriRequest buildRequest(final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions);
}
