// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.WorkbookChartDataLabelFormat;
import com.microsoft.graph.requests.extensions.IWorkbookChartFillRequestBuilder;
import com.microsoft.graph.requests.extensions.IWorkbookChartFontRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.models.extensions.WorkbookChartDataLabelFormat;
import com.microsoft.graph.http.IHttpRequest;
import com.microsoft.graph.serializer.IJsonBackedObject;


// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Workbook Chart Data Label Format With Reference Request.
 */
public interface IWorkbookChartDataLabelFormatWithReferenceRequest extends IHttpRequest {

    void post(final WorkbookChartDataLabelFormat newWorkbookChartDataLabelFormat, final IJsonBackedObject payload, final ICallback<? super WorkbookChartDataLabelFormat> callback);

    WorkbookChartDataLabelFormat post(final WorkbookChartDataLabelFormat newWorkbookChartDataLabelFormat, final IJsonBackedObject payload) throws ClientException;

    void get(final ICallback<? super WorkbookChartDataLabelFormat> callback);

    WorkbookChartDataLabelFormat get() throws ClientException;

	void delete(final ICallback<? super WorkbookChartDataLabelFormat> callback);

	void delete() throws ClientException;

	void patch(final WorkbookChartDataLabelFormat sourceWorkbookChartDataLabelFormat, final ICallback<? super WorkbookChartDataLabelFormat> callback);

	WorkbookChartDataLabelFormat patch(final WorkbookChartDataLabelFormat sourceWorkbookChartDataLabelFormat) throws ClientException;

    IWorkbookChartDataLabelFormatWithReferenceRequest select(final String value);

    IWorkbookChartDataLabelFormatWithReferenceRequest expand(final String value);

}
