// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.WorkbookChartGridlinesFormat;
import com.microsoft.graph.requests.extensions.IWorkbookChartLineFormatRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.models.extensions.WorkbookChartGridlinesFormat;
import com.microsoft.graph.http.IHttpRequest;
import com.microsoft.graph.serializer.IJsonBackedObject;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Workbook Chart Gridlines Format Reference Request.
 */
public interface IWorkbookChartGridlinesFormatReferenceRequest extends IHttpRequest {

    void delete(final ICallback<? super WorkbookChartGridlinesFormat> callback);

    WorkbookChartGridlinesFormat delete() throws ClientException;

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    IWorkbookChartGridlinesFormatReferenceRequest select(final String value);

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    IWorkbookChartGridlinesFormatReferenceRequest expand(final String value);

    /**
     * Puts the WorkbookChartGridlinesFormat
     *
     * @param srcWorkbookChartGridlinesFormat the WorkbookChartGridlinesFormat to PUT
     * @param callback the callback to be called after success or failure
     */
    void put(WorkbookChartGridlinesFormat srcWorkbookChartGridlinesFormat, final ICallback<? super WorkbookChartGridlinesFormat> callback);

    /**
     * Puts the WorkbookChartGridlinesFormat
     *
     * @param srcWorkbookChartGridlinesFormat the WorkbookChartGridlinesFormat to PUT
     * @return the WorkbookChartGridlinesFormat
     * @throws ClientException an exception occurs if there was an error while the request was sent
     */
    WorkbookChartGridlinesFormat put(WorkbookChartGridlinesFormat srcWorkbookChartGridlinesFormat) throws ClientException;
}
