// Template Source: BaseEntityCollectionPage.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.models.extensions.ThreatAssessmentRequest;
import com.microsoft.graph.requests.extensions.IThreatAssessmentRequestCollectionRequestBuilder;
import com.microsoft.graph.http.BaseCollectionPage;
import com.microsoft.graph.requests.extensions.ThreatAssessmentRequestCollectionPage;
import com.microsoft.graph.requests.extensions.ThreatAssessmentRequestCollectionResponse;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Threat Assessment Request Collection Page.
 */
public class ThreatAssessmentRequestCollectionPage extends BaseCollectionPage<ThreatAssessmentRequest, IThreatAssessmentRequestCollectionRequestBuilder> implements IThreatAssessmentRequestCollectionPage {

    /**
     * A collection page for ThreatAssessmentRequest
     *
     * @param response the serialized ThreatAssessmentRequestCollectionResponse from the service
     * @param builder  the request builder for the next collection page
     */
    public ThreatAssessmentRequestCollectionPage(final ThreatAssessmentRequestCollectionResponse response, final IThreatAssessmentRequestCollectionRequestBuilder builder) {
        super(response.value, builder, response.additionalDataManager());
    }
}
