// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.TimeOff;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.options.QueryOption;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;
import com.microsoft.graph.core.IBaseClient;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Time Off Reference Request.
 */
public class TimeOffReferenceRequest extends BaseRequest implements ITimeOffReferenceRequest {

    /**
     * The request for the TimeOff
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public TimeOffReferenceRequest(String requestUrl, IBaseClient client, java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, TimeOff.class);
    }

    public void delete(final ICallback<? super TimeOff> callback) {
        send(HttpMethod.DELETE, callback, null);
    }

    public TimeOff delete() throws ClientException {
       return send(HttpMethod.DELETE, null);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    public ITimeOffReferenceRequest select(final String value) {
        getQueryOptions().add(new com.microsoft.graph.options.QueryOption("$select", value));
        return (TimeOffReferenceRequest)this;
    }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    public ITimeOffReferenceRequest expand(final String value) {
        getQueryOptions().add(new com.microsoft.graph.options.QueryOption("$expand", value));
        return (TimeOffReferenceRequest)this;
    }
    /**
     * Puts the TimeOff
     *
     * @param srcTimeOff the TimeOff reference to PUT
     * @param callback the callback to be called after success or failure
     */
    public void put(TimeOff srcTimeOff, final ICallback<? super TimeOff> callback) {
        send(HttpMethod.PUT, callback, srcTimeOff);
    }

    /**
     * Puts the TimeOff
     *
     * @param srcTimeOff the TimeOff reference to PUT
     * @return the TimeOff
     * @throws ClientException an exception occurs if there was an error while the request was sent
     */
    public TimeOff put(TimeOff srcTimeOff) throws ClientException {
        return send(HttpMethod.PUT, srcTimeOff);
    }
}
