// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.WorkbookTableColumn;
import com.microsoft.graph.models.extensions.WorkbookRange;
import com.microsoft.graph.requests.extensions.IWorkbookFilterRequestBuilder;
import com.microsoft.graph.requests.extensions.WorkbookFilterRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.options.QueryOption;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;
import com.microsoft.graph.core.IBaseClient;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Workbook Table Column Reference Request.
 */
public class WorkbookTableColumnReferenceRequest extends BaseRequest implements IWorkbookTableColumnReferenceRequest {

    /**
     * The request for the WorkbookTableColumn
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public WorkbookTableColumnReferenceRequest(String requestUrl, IBaseClient client, java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, WorkbookTableColumn.class);
    }

    public void delete(final ICallback<? super WorkbookTableColumn> callback) {
        send(HttpMethod.DELETE, callback, null);
    }

    public WorkbookTableColumn delete() throws ClientException {
       return send(HttpMethod.DELETE, null);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    public IWorkbookTableColumnReferenceRequest select(final String value) {
        getQueryOptions().add(new com.microsoft.graph.options.QueryOption("$select", value));
        return (WorkbookTableColumnReferenceRequest)this;
    }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    public IWorkbookTableColumnReferenceRequest expand(final String value) {
        getQueryOptions().add(new com.microsoft.graph.options.QueryOption("$expand", value));
        return (WorkbookTableColumnReferenceRequest)this;
    }
    /**
     * Puts the WorkbookTableColumn
     *
     * @param srcWorkbookTableColumn the WorkbookTableColumn reference to PUT
     * @param callback the callback to be called after success or failure
     */
    public void put(WorkbookTableColumn srcWorkbookTableColumn, final ICallback<? super WorkbookTableColumn> callback) {
        send(HttpMethod.PUT, callback, srcWorkbookTableColumn);
    }

    /**
     * Puts the WorkbookTableColumn
     *
     * @param srcWorkbookTableColumn the WorkbookTableColumn reference to PUT
     * @return the WorkbookTableColumn
     * @throws ClientException an exception occurs if there was an error while the request was sent
     */
    public WorkbookTableColumn put(WorkbookTableColumn srcWorkbookTableColumn) throws ClientException {
        return send(HttpMethod.PUT, srcWorkbookTableColumn);
    }
}
