// Template Source: BaseEntity.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models;
import com.microsoft.graph.serializer.ISerializer;
import com.microsoft.graph.serializer.IJsonBackedObject;
import com.microsoft.graph.serializer.AdditionalDataManager;
import java.util.EnumSet;
import com.microsoft.graph.models.PayloadDetail;


import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Email Payload Detail.
 */
public class EmailPayloadDetail extends PayloadDetail implements IJsonBackedObject {


    /**
     * The From Email.
     * 
     */
    @SerializedName(value = "fromEmail", alternate = {"FromEmail"})
    @Expose
	@Nullable
    public String fromEmail;

    /**
     * The From Name.
     * 
     */
    @SerializedName(value = "fromName", alternate = {"FromName"})
    @Expose
	@Nullable
    public String fromName;

    /**
     * The Is External Sender.
     * 
     */
    @SerializedName(value = "isExternalSender", alternate = {"IsExternalSender"})
    @Expose
	@Nullable
    public Boolean isExternalSender;

    /**
     * The Subject.
     * 
     */
    @SerializedName(value = "subject", alternate = {"Subject"})
    @Expose
	@Nullable
    public String subject;


    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(@Nonnull final ISerializer serializer, @Nonnull final JsonObject json) {

    }
}
