// Template Source: BaseEntityCollectionWithReferencesPage.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.EmployeeExperienceUser;
import com.microsoft.graph.models.LearningCourseActivity;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.requests.LearningCourseActivityCollectionWithReferencesRequestBuilder;
import com.microsoft.graph.requests.LearningCourseActivityCollectionWithReferencesPage;
import com.microsoft.graph.requests.LearningCourseActivityCollectionResponse;
import com.microsoft.graph.models.LearningCourseActivity;
import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import com.microsoft.graph.http.BaseCollectionPage;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Learning Course Activity Collection With References Page.
 */
public class LearningCourseActivityCollectionWithReferencesPage extends BaseCollectionPage<LearningCourseActivity, LearningCourseActivityCollectionWithReferencesRequestBuilder> {

    /**
     * A collection page for LearningCourseActivity
     *
     * @param response the serialized LearningCourseActivityCollectionResponse from the service
     * @param builder  the request builder for the next collection page
     */
    public LearningCourseActivityCollectionWithReferencesPage(@Nonnull final LearningCourseActivityCollectionResponse response, @Nullable final LearningCourseActivityCollectionWithReferencesRequestBuilder builder) {
        super(response.value, builder, response.additionalDataManager());
    }

    /**
     * Creates the collection page for LearningCourseActivity
     *
     * @param pageContents       the contents of this page
     * @param nextRequestBuilder the request builder for the next page
     */
    public LearningCourseActivityCollectionWithReferencesPage(@Nonnull final java.util.List<LearningCourseActivity> pageContents, @Nullable final LearningCourseActivityCollectionWithReferencesRequestBuilder nextRequestBuilder) {
        super(pageContents, nextRequestBuilder);
    }
}
