// Template Source: BaseEntityCollectionPage.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;
import com.microsoft.graph.models.Payload;
import com.microsoft.graph.requests.PayloadCollectionRequestBuilder;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.requests.PayloadCollectionResponse;
import com.microsoft.graph.http.BaseCollectionPage;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Payload Collection Page.
 */
public class PayloadCollectionPage extends BaseCollectionPage<Payload, PayloadCollectionRequestBuilder> {

    /**
     * A collection page for Payload
     *
     * @param response the serialized PayloadCollectionResponse from the service
     * @param builder  the request builder for the next collection page
     */
    public PayloadCollectionPage(@Nonnull final PayloadCollectionResponse response, @Nonnull final PayloadCollectionRequestBuilder builder) {
        super(response, builder);
    }

    /**
     * Creates the collection page for Payload
     *
     * @param pageContents       the contents of this page
     * @param nextRequestBuilder the request builder for the next page
     */
    public PayloadCollectionPage(@Nonnull final java.util.List<Payload> pageContents, @Nullable final PayloadCollectionRequestBuilder nextRequestBuilder) {
        super(pageContents, nextRequestBuilder);
    }
}
