// Template Source: BaseMethodCollectionPage.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.ArchivedPrintJob;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.http.BaseCollectionPage;
import com.microsoft.graph.requests.ReportRootGetPrinterArchivedPrintJobsCollectionRequestBuilder;
import com.microsoft.graph.requests.ReportRootGetPrinterArchivedPrintJobsCollectionPage;
import com.microsoft.graph.requests.ReportRootGetPrinterArchivedPrintJobsCollectionResponse;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Report Root Get Printer Archived Print Jobs Collection Page.
 */
public class ReportRootGetPrinterArchivedPrintJobsCollectionPage extends BaseCollectionPage<ArchivedPrintJob, ReportRootGetPrinterArchivedPrintJobsCollectionRequestBuilder> {

    /**
     * A collection page for ArchivedPrintJob.
     *
     * @param response The serialized ReportRootGetPrinterArchivedPrintJobsCollectionResponse from the service
     * @param builder The request builder for the next collection page
     */
    public ReportRootGetPrinterArchivedPrintJobsCollectionPage(@Nonnull final ReportRootGetPrinterArchivedPrintJobsCollectionResponse response, @Nonnull final ReportRootGetPrinterArchivedPrintJobsCollectionRequestBuilder builder) {
       super(response, builder);
    }

	/**
     * Creates the collection page for ReportRootGetPrinterArchivedPrintJobs
     *
     * @param pageContents       the contents of this page
     * @param nextRequestBuilder the request builder for the next page
     */
    public ReportRootGetPrinterArchivedPrintJobsCollectionPage(@Nonnull final java.util.List<ArchivedPrintJob> pageContents, @Nullable final ReportRootGetPrinterArchivedPrintJobsCollectionRequestBuilder nextRequestBuilder) {
        super(pageContents, nextRequestBuilder);
    }
}
