// Template Source: BaseEntityCollectionRequestBuilder.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.ediscovery.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.ediscovery.models.Case;
import com.microsoft.graph.ediscovery.models.ReviewSet;
import com.microsoft.graph.ediscovery.models.SourceCollection;
import com.microsoft.graph.ediscovery.models.AdditionalDataOptions;
import java.util.EnumSet;
import com.microsoft.graph.ediscovery.models.ExportOptions;
import com.microsoft.graph.ediscovery.models.ExportFileStructure;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.ediscovery.requests.ReviewSetCollectionRequestBuilder;
import com.microsoft.graph.ediscovery.requests.ReviewSetRequestBuilder;
import com.microsoft.graph.ediscovery.requests.ReviewSetCollectionRequest;
import com.microsoft.graph.http.BaseCollectionRequestBuilder;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.PrimitiveRequestBuilder;
import com.microsoft.graph.ediscovery.models.ReviewSetAddToReviewSetParameterSet;
import com.microsoft.graph.ediscovery.models.ReviewSetExportParameterSet;
// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Review Set Collection Request Builder.
 */
public class ReviewSetCollectionRequestBuilder extends BaseCollectionRequestBuilder<ReviewSet, ReviewSetRequestBuilder, ReviewSetCollectionResponse, ReviewSetCollectionPage, ReviewSetCollectionRequest> {

    /**
     * The request builder for this collection of Case
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public ReviewSetCollectionRequestBuilder(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, ReviewSetRequestBuilder.class, ReviewSetCollectionRequest.class);
    }



    /**
     * Gets the raw count request for the collection
     * @return The raw count request for the collection
     */
    @Nonnull
    public PrimitiveRequestBuilder<Long> count() {
        return new PrimitiveRequestBuilder<Long>(getRequestUrlWithAdditionalSegment("$count"), getClient(), null, Long.class);
    }
}
