trigger: none
pr: none

schedules:
  - cron: '0 0 * * *'
    displayName: Daily builds
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: ubuntu-latest
      os: linux
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows
      credscan:
        enabled: true
      policheck:
        enabled: true
      binskim:
        enabled: true
    stages:
      - stage: Build
        jobs:
          - job: Build
            displayName: Build Java SDK
            steps:
              - checkout: self
                submodules: recursive

              - script: |
                  sed -i "/mavenCentral()/d" build.gradle
                  sed -i "/gradlePluginPortal()/d" settings.gradle
                  sed -i "/mavenCentral()/d" settings.gradle
                displayName: Strip plugins and public repos for network-isolated build

              - task: Gradle@4
                displayName: Build and Test SDK
                inputs:
                  gradleWrapperFile: 'gradlew'
                  workingDirectory: '$(Build.SourcesDirectory)'
                  tasks: 'assemble test'
                  options: '--no-daemon -PGraphDeveloperExperiencesPublicPassword=$(ARTIFACTS_PAT)'
                  publishJUnitResults: true
                  testResultsFiles: '**/TEST-*.xml'
                  javaHomeOption: 'JDKVersion'
                  jdkVersionOption: '1.17'
                  jdkArchitectureOption: 'x64'
